import type { AxiosInstance, AxiosError, InternalAxiosRequestConfig } from 'axios';
import axios, { AxiosHeaders } from 'axios';

const META_SELECTOR = 'meta[name="csrf-token"]';

/** The CSRF token rendered into the page <meta> at load (may go stale). */
export function csrfToken(): string | undefined {
    return document.querySelector<HTMLMetaElement>(META_SELECTOR)?.content;
}

function setMetaToken(token: string): void {
    const el = document.querySelector<HTMLMetaElement>(META_SELECTOR);

    if (el) {
        el.content = token;
    }
}

// Mark a request config so it's only ever retried once (no 419 loop).
type RetriableConfig = InternalAxiosRequestConfig & { __csrfRetried?: boolean };

/**
 * Rejection handler for a 419 (CSRF token mismatch): fetch the live token,
 * refresh the <meta> and the failed request's header, then retry the request
 * once. A 419 means the session is valid but the page's token is stale (page
 * left open a while, or the session token was regenerated by a re-auth in
 * another tab) — without this every store mutation wedges until a full reload.
 */
export function makeCsrf419Handler(client: AxiosInstance) {
    return async (error: AxiosError): Promise<unknown> => {
        const config = error.config as RetriableConfig | undefined;

        if (error.response?.status !== 419 || !config || config.__csrfRetried) {
            return Promise.reject(error);
        }

        config.__csrfRetried = true;

        let token: string | undefined;

        try {
            const { data } = await client.get<{ token?: string }>('/csrf-token');
            token = data?.token;
        } catch {
            return Promise.reject(error); // refresh failed — surface the original 419.
        }

        if (!token) {
            return Promise.reject(error);
        }

        setMetaToken(token);
        config.headers = AxiosHeaders.from(config.headers);
        config.headers.set('X-CSRF-TOKEN', token);

        return client(config);
    };
}

/** Register the 419-retry interceptor on the shared axios instance (once). */
export function installCsrfRetry(client: AxiosInstance = axios): void {
    client.interceptors.response.use((r) => r, makeCsrf419Handler(client));
}
